In [1]:
import numpy as np

🌟 **Exercise 1** : Array Creation and Manipulation

In [2]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


🌟 **Exercise 2** : Type Conversion and Array Operations

In [3]:
my_list = [3.14, 2.17, 0, 1, 2]

array = np.array(my_list)
print(array)
print(array.dtype)

# Converting to integer
array = array.astype(int)
print(array)
print(array.dtype)


[3.14 2.17 0.   1.   2.  ]
float64
[3 2 0 1 2]
int64


🌟 **Exercise 3** : Working with Multi-Dimensional Arrays

In [4]:
array_3x3 = np.arange(1,10).reshape(3,3)
print(array_3x3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 **Exercise 4** : Creating Multi-Dimensional Array with Random Numbers

In [5]:
import random

array_2D = np.array(np.random.rand(4,5))
array_2D = np.round(array_2D, 2)
print(array_2D)

[[0.49 0.8  0.94 0.5  0.95]
 [0.39 0.49 0.1  0.2  0.92]
 [0.44 0.79 0.62 0.7  0.81]
 [0.93 0.89 0.18 0.27 0.14]]


🌟 **Exercise 5** : Indexing Arrays

In [6]:
array = np.array(np.random.randint(0, 100, size=(4,5)))
print(array)

print(array[1, :])

[[52 68 26 20  0]
 [35  1 68 57 53]
 [82 42 32 96  6]
 [75 75 51 66 20]]
[35  1 68 57 53]


🌟 **Exercise 6** : Reversing elements

In [7]:
array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
print(array)

reversed_array = array[::-1]
# reversed_array = np.flip(array)
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


🌟 **Exercise 7** : Identity Matrix

In [8]:
array = np.array(np.identity(4))
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 **Exercise 8** : Simple Aggregate Funcs

In [9]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Sum", np.sum(my_array))
print("Average", np.mean(my_array))

Sum 45
Average 4.5


🌟 **Exercise 9** : Create Array and Change its Structure

In [10]:
my_array = np.arange(1, 21)
my_array = my_array.reshape(4,5)
print(my_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 **Exercise 10** : Conditional Selection of Values

In [11]:
array = np.arange(10)
print(array)

array_odd = array[array%2 != 0]
print(array_odd)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
